# Generated by Django 5.2.17 on 2026-09-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_school_administrators_group'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='school',
            constraint=models.CheckConstraint(condition=models.Q(('singleton_id', 1)), name='school_singleton_id_must_be_constant'),
        ),
    ]
