# Generated by Django 5.2.17 on 2026-09-22 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_school_school_singleton_id_must_be_constant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class/Grade',
                'verbose_name_plural': 'Classes/Grades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='core.classgrade')),
            ],
            options={
                'ordering': ['class_grade', 'name'],
                'constraints': [models.UniqueConstraint(fields=('class_grade', 'name'), name='section_unique_name_per_class_grade')],
            },
        ),
    ]
