# Generated by Django 5.2.17 on 2026-09-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_applicant_guardian_permissions_to_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='admission_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
