# Generated by Django 5.2.17 on 2026-09-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_academicenrollment_permissions_to_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
